### ISSUE TITLE
Missing/incorrect default 'period' facet for ds(project='CMIP6') ?

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#189]
@jservonnat I have started experimenting with CliMAF on ciclad (`module load climaf/2.0.0-python3.6`), in order to check the available _PMIP_ data

I think there may be a missing (or incorrectly initialized) CMIP6 dataset facet: `period`

I get an error message if I don't specify a value for `period`:
```
>>> exp_name, var_name, cmip_table
('midHolocene', 'pr', 'Amon')
>>> default_query = dict(project = 'CMIP6',
...                      experiment = exp_name,
...                      variable = var_name,
...                      table = cmip_table,
... )
>>>
>>> my_query = ds(model='*', **default_query)
Traceback (most recent call last):
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/period.py", line 228, in init_period
    s = datetime.datetime(year=syear, month=smonth, day=sday, hour=shour, minute=sminute)
ValueError: year 0 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/classes.py", line 1520, in ds
    return cdataset(**select_projects(**kwargs))
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/classes.py", line 376, in __init__
    attval = processDatasetArgs(**kwargs)
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/classes.py", line 309, in processDatasetArgs
    attval['period'] = init_period(attval['period'])
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/period.py", line 231, in init_period
    "period start string %s is not a date (%s %s %s %s %s)" % (start, syear, smonth, sday, shour, sminute))
climaf.period.Climaf_Period_Error: 'period start string 0000 is not a date (0 1 1 0 0)'
```
But it's OK, if I add `period='*'` to my query
```
>>> my_query = ds(model='*', period='*', **default_query)
>>> my_query.explore('choices')['period']
[0001-1700, 1798-2401, 2404-2410, 2412-2414, 2418-2424, 2427-2431, 2434-2437, 2439-2441, 2443-2445, 2447, 2900-2999, 3106-3205, 8000-8099]
```

**Comment by jypeter** [comment]
After reading `cdef` documentation, I have found that **the default `period` is an empty string**, whereas the default `model` (for example) is a wildcard
```
>>> cdef('period', project='CMIP5')
''
>>> cdef('period', project='CMIP6')
''
>>> cdef('model', project='CMIP6')
'*'
```
