### ISSUE TITLE
cfile(some_ds) crashes if the dataset uses period='*'

### ISSUE THREAD

**Issue by jypeter** [rigoudyg/climaf#201]
When using a dataset where `period='*'`, but there is no real ambiguity in the dataset (`summary` does not complain and `explore('choices')` does not show multiple options), I get a frightening traceback when using `cfile` or other operators.

Things are OK once I use _‘resolve’ for returning a NEW DATASET with instanciated attributes_

There is probably some logic behind this, but it would be **extremely helpful** for the end user if this ambiguity problem was detected (and possibly automatically resolved) and **if CliMAF could display a nice warning message instead of crashing**

Detailed example below 

```
[jypmce@ciclad-ng ~]$ module load climaf/2.0.0-python3.6
Loading climaf/2.0.0-python3.6
  Loading requirement: nco/4.5.2 ncl/6.3.0 cdo/1.9 netcdf4/4.3.3.1-gfortran

[...]

>>> from climaf.api import *

[...]

>>> kvp_restore = {'project': 'CMIP6', 'simulation': '', 'variable': 'pr', 'period': '*', 'domain': 'global', 'root': '/bdd', 'model': 'IPSL-CM6A-LR', 'institute': '*', 'mip': '*', 'table': 'Amon', 'experiment': 'midHolocene', 'realization': 'r1i1p1f1', 'grid': 'gr', 'version': 'latest'}

>>> pmip_test = ds(**kvp_restore)
>>> pmip_test
ds('CMIP6%%pr%*%global%/bdd%IPSL-CM6A-LR%*%*%Amon%midHolocene%r1i1p1f1%gr%latest')

>>> pmip_test.explore('choices')
{'period': [1850-2399], 'institute': 'IPSL', 'mip': 'PMIP'}

>>> summary(pmip_test)
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_185001-204912.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_205001-234812.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_234901-234912.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_235001-239912.nc
{'project': 'CMIP6', 'simulation': '', 'variable': 'pr', 'period': '*', 'domain': 'global', 'root': '/bdd', 'model': 'IPSL-CM6A-LR', 'institute': '*', 'mip': '*', 'table': 'Amon', 'experiment': 'midHolocene', 'realization': 'r1i1p1f1', 'grid': 'gr', 'version': 'latest'}

>>> cfile_attempt_1 = cfile(pmip_test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 1199, in cfile
    result = ceval(object, format='file', deep=deep)
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 665, in ceval
    derived_list=derived_list, recurse_list=recurse_list)
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 270, in ceval_for_cdataset
    rep = ceval(extract, userflags=userflags, format=format)
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 669, in ceval
    derived_list=derived_list, recurse_list=recurse_list)
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 387, in ceval_for_ctree
    recurse_list=recurse_list)  # Does return a filename, or list of filenames
  File "/ciclad-home/jservon/Evaluation/CliMAF/climaf_installs/climaf_V2.0.0/climaf/driver.py", line 761, in ceval_script
    if per and not per.fx and str(per) != "" and scriptCall.flags.canSelectTime:
AttributeError: 'str' object has no attribute 'fx'

>>> pmip_test_resolved = pmip_test.explore('resolve')

>>> pmip_test_resolved
ds('CMIP6%%pr%1850-2399%global%/bdd%IPSL-CM6A-LR%IPSL%PMIP%Amon%midHolocene%r1i1p1f1%gr%latest')

>>> pmip_test_resolved.explore('choices')
{}

>>> summary(pmip_test_resolved)
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_185001-204912.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_205001-234812.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_234901-234912.nc
/bdd/CMIP6/PMIP/IPSL/IPSL-CM6A-LR/midHolocene/r1i1p1f1/Amon/pr/gr/latest/pr_Amon_IPSL-CM6A-LR_midHolocene_r1i1p1f1_gr_235001-239912.nc
{'project': 'CMIP6', 'simulation': '', 'variable': 'pr', 'period': 1850-2399, 'domain': 'global', 'root': '/bdd', 'model': 'IPSL-CM6A-LR', 'institute': 'IPSL', 'mip': 'PMIP', 'table': 'Amon', 'experiment': 'midHolocene', 'realization': 'r1i1p1f1', 'grid': 'gr', 'version': 'latest'}

>>> cfile_attempt_2 = cfile(pmip_test_resolved)
>>> cfile_attempt_2
'/data/jypmce/climafcache/65/1b618d5501ba62a63336104e811fdd40fc8161761df77b53f9091a.nc'
>>>
```

**Comment by rigoudyg** [comment]
@jypeter 
The PR #211 should solve this issue.
Can you check that on your side?
